### ISSUE TITLE
Create sample application with file inputs and job parameters

### ISSUE THREAD

**Issue by jchuahtacc** [tapis-project/tapis-ui#116]
Create a sample application available to cicsvc on the tacc tenant that accepts file inputs and job parameters, to be used for integration testing and to have a TAPIS object to code against

**Comment by nathandf** [comment]
Tenant: tacc.tapis.io

App: 
id: bsf
version: 1
url: https://tacc.tapis.io/v3/apps/bsf/1

System:
id: testuser2.execution
url: https://tacc.tapis.io/v3/systems/testuser2.exection

User: cicsvc
Perms: [ READ, EXECUTE ]
