### ISSUE TITLE
Config object overrides of tapis-redux configuration should be key based

### ISSUE THREAD

**Issue by jchuahtacc** [tapis-project/tapis-ui#15]
Currently, if values in `config` objects are falsy, they are overridden. This is undesirable because an external state manager may set a value like `token` to be null to indicate a logout, but `tapis-redux` will currently fall back upon the internally stored `token` state and perform operations anyway.

`tapis-redux` should:
- Check for key values in `config`
- If a key value is present, always use it in an override even if the value is falsy (this will generate errors, but that is fine and should be expected)
- If a key value is not present use the fallback values such as `token` state and tenant URL

**Comment by joestubbs** [comment]
not relevant
