### ISSUE TITLE
Bug: forwardslash missing in File Inputs SourceURL

### ISSUE THREAD

**Issue by tacc-afields** [tapis-project/tapis-ui#343]
In the File Inputs section, when using the SourceURL, the forwardslash after the system Name is left off.
Example:
tapis://af_test_system/test_directory/test1.txt
is populated as
tapis://af_test_systemtest_directory/test1.txt

**Comment by carrythemountain** [comment]
FILES MODAL MISSING : or / AFTER “Files”
Should be select system -> select file
AFTER SYSTEM Selected -> select file
/ missing after first file path

EX:

It should be 
Files: tapisv3-exec2-demo-final/finaltest/file1.txt
not 
Files tapisv3-exec2-demo-finalfinaltest/file1.txt
