### ISSUE TITLE
Breadcrumbs issue with models containing '/'

### ISSUE THREAD

**Issue by carrythemountain** [tapis-project/tapis-ui#378]
The Breadcrumbs is broken in the model details page because it takes a naive approach to splitting the path into parts. 

For example, if you give it a modelId that contains a / :
 `ex: google/somemodel` 

it will break that up into 2 links 

`MLHub` / `models` / `google` / somemodel. 

Clicking the google link breaks the UI.
We need a way to tell the breadcrumbs that fragments `google` and `somemodel` should be joined into 1 fragment.

**Comment by carrythemountain** [comment]
https://github.com/tapis-project/tapis-ui/assets/170014805/9cb05ead-de6a-4fa0-8f91-31daf4e05563

**Comment by carrythemountain** [comment]
Uploading Screen Recording 2024-05-31 at 2.47.19 PM.mov…

**Comment by NotChristianGarcia** [comment]
Oh hi! Pods deals with this.
For example, breadcrumbs work here: https://tacc.develop.tapis.io/tapis-ui/#/pods/images/dhannywi/inference-api
![image](https://github.com/user-attachments/assets/b1c9438b-5a39-47c4-9c05-0f7e57268d8b)


I added a handy if statement for `/pods/images` that essentially slices pods, images, and remaining. [This is the commit](https://github.com/tapis-project/tapis-ui/commit/f04e51bba08236f2f4e9718f8f38dd4e5c494586). Changes to `lib/tapisui-common/src/ui/Breadcrumbs/breadcrumbsFromPathname.ts` mattered the most.

**Comment by NotChristianGarcia** [comment]
22db795f81203ef7f510466104e894ee215f2d56 Committed! Made changes for ML-Hub models and datasets!
