### ISSUE TITLE
SGX3 - Render secondary sidebar items in collapsible component on sidebar

### ISSUE THREAD

**Issue by nathandf** [tapis-project/tapis-ui#392]
[Secondary sidebar items](https://github.com/tapis-project/tapis-ui/blob/08a33f5bc66514ed490a492946f89c833c793f9a/src/app/_components/Sidebar/Sidebar.tsx#L70)

Render any/all secondarySidebarItems in some collapsible component below the mainSidebarItems

**Comment by NotChristianGarcia** [comment]
![image](https://github.com/user-attachments/assets/f5062726-886a-483a-82fe-b143dec17d31)
